apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  labels:
    app: reactapp-portfolio-via-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp-portfolio-via-jenkins
  template:
    metadata:
      labels:
        app: reactapp-portfolio-via-jenkins
    spec:
      containers:
      - name: reactapp-portfolio-via-jenkins
        image: manojtiwari000/reactapp:v2
        ports:
        - containerPort: 3000

