apiVersion: v1
kind: Service
metadata:
  name: react-app-portfolio-service
spec:
  selector:
    app: reactapp-portfolio-via-jenkins
  ports:
    - protocol: TCP
      port: 80  # Port you want to expose on the service
      targetPort: 3000  # Port your app listens on
  type: LoadBalancer  # Type of service (LoadBalancer, NodePort, ClusterIP, etc.)

